DROP TABLE IF EXISTS shows;
CREATE TABLE shows (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    banda TEXT NOT NULL,
    local TEXT NOT NULL,
    data TEXT NOT NULL
);

INSERT INTO shows (banda, local, data) VALUES ('Didi Caruaru', 'Caruaru - Alto do Moura', '2026-06-06');
INSERT INTO shows (banda, local, data) VALUES ('Arreio de Ouro', 'Caruaru - Alto do Moura', '2026-06-06');
INSERT INTO shows (banda, local, data) VALUES ('Targino Gondim', 'Caruaru - Alto do Moura', '2026-06-06');
INSERT INTO shows (banda, local, data) VALUES ('Walkiria Santos', 'Caruaru - Alto do Moura', '2026-06-06');
INSERT INTO shows (banda, local, data) VALUES ('Toca do Vale', 'Caruaru - Alto do Moura', '2026-06-07');
INSERT INTO shows (banda, local, data) VALUES ('Geraldinho Lins', 'Caruaru - Alto do Moura', '2026-06-07');
INSERT INTO shows (banda, local, data) VALUES ('Eliane', 'Caruaru - Alto do Moura', '2026-06-07');
INSERT INTO shows (banda, local, data) VALUES ('Gatinha Manhosa', 'Caruaru - Alto do Moura', '2026-06-13');
INSERT INTO shows (banda, local, data) VALUES ('Waldonys', 'Caruaru - Alto do Moura', '2026-06-13');
INSERT INTO shows (banda, local, data) VALUES ('Edy e Natan', 'Caruaru - Alto do Moura', '2026-06-13');
INSERT INTO shows (banda, local, data) VALUES ('Santanna, O Cantador', 'Caruaru - Alto do Moura', '2026-06-14');
INSERT INTO shows (banda, local, data) VALUES ('Fernandinha', 'Caruaru - Alto do Moura', '2026-06-14');
INSERT INTO shows (banda, local, data) VALUES ('Juarez', 'Caruaru - Alto do Moura', '2026-06-14');
INSERT INTO shows (banda, local, data) VALUES ('Petrúcio Amorim', 'Caruaru - Alto do Moura', '2026-06-20');
INSERT INTO shows (banda, local, data) VALUES ('Noda de Caju', 'Caruaru - Alto do Moura', '2026-06-20');
INSERT INTO shows (banda, local, data) VALUES ('Garota Safada', 'Caruaru - Alto do Moura', '2026-06-20');
INSERT INTO shows (banda, local, data) VALUES ('Matheus Vinni', 'Caruaru - Alto do Moura', '2026-06-21');
INSERT INTO shows (banda, local, data) VALUES ('Forró da Brucelose', 'Caruaru - Alto do Moura', '2026-06-21');
INSERT INTO shows (banda, local, data) VALUES ('Novinho da Paraíba', 'Caruaru - Alto do Moura', '2026-06-21');
INSERT INTO shows (banda, local, data) VALUES ('Israel Filho', 'Caruaru - Alto do Moura', '2026-06-23');
INSERT INTO shows (banda, local, data) VALUES ('Assisão', 'Caruaru - Alto do Moura', '2026-06-23');
INSERT INTO shows (banda, local, data) VALUES ('Vilões do Forró', 'Caruaru - Alto do Moura', '2026-06-23');
INSERT INTO shows (banda, local, data) VALUES ('Renatto Pires', 'Caruaru - Alto do Moura', '2026-06-24');
INSERT INTO shows (banda, local, data) VALUES ('Thullio Milionário', 'Caruaru - Alto do Moura', '2026-06-24');
INSERT INTO shows (banda, local, data) VALUES ('Cavalo de Pau', 'Caruaru - Alto do Moura', '2026-06-24');
INSERT INTO shows (banda, local, data) VALUES ('Douglas Leon', 'Caruaru - Alto do Moura', '2026-06-27');
INSERT INTO shows (banda, local, data) VALUES ('Baby Som', 'Caruaru - Alto do Moura', '2026-06-27');
INSERT INTO shows (banda, local, data) VALUES ('Edylla e Levy', 'Caruaru - Azulão', '2026-05-28');
INSERT INTO shows (banda, local, data) VALUES ('Eli Soares', 'Caruaru - Azulão', '2026-05-28');
INSERT INTO shows (banda, local, data) VALUES ('Davi Sacer', 'Caruaru - Azulão', '2026-05-28');
INSERT INTO shows (banda, local, data) VALUES ('Rolê Alternativo', 'Caruaru - Azulão', '2026-06-04');
INSERT INTO shows (banda, local, data) VALUES ('Segundo Turno', 'Caruaru - Azulão', '2026-06-04');
INSERT INTO shows (banda, local, data) VALUES ('Perpetuo Insigne', 'Caruaru - Azulão', '2026-06-04');
INSERT INTO shows (banda, local, data) VALUES ('Inanna', 'Caruaru - Azulão', '2026-06-04');
INSERT INTO shows (banda, local, data) VALUES ('Uptown Blues Band', 'Caruaru - Azulão', '2026-06-04');
INSERT INTO shows (banda, local, data) VALUES ('Gabriel Sá', 'Caruaru - Azulão', '2026-06-05');
INSERT INTO shows (banda, local, data) VALUES ('Erisson Porto', 'Caruaru - Azulão', '2026-06-05');
INSERT INTO shows (banda, local, data) VALUES ('Big Band A Nordestina', 'Caruaru - Azulão', '2026-06-05');
INSERT INTO shows (banda, local, data) VALUES ('Falamansa', 'Caruaru - Azulão', '2026-06-05');
INSERT INTO shows (banda, local, data) VALUES ('Amanan', 'Caruaru - Azulão', '2026-06-06');
INSERT INTO shows (banda, local, data) VALUES ('Rogéria Dera', 'Caruaru - Azulão', '2026-06-06');
INSERT INTO shows (banda, local, data) VALUES ('Almério', 'Caruaru - Azulão', '2026-06-06');
INSERT INTO shows (banda, local, data) VALUES ('Lucy Alves', 'Caruaru - Azulão', '2026-06-06');
INSERT INTO shows (banda, local, data) VALUES ('Black Diary', 'Caruaru - Azulão', '2026-06-11');
INSERT INTO shows (banda, local, data) VALUES ('O Bacamarte', 'Caruaru - Azulão', '2026-06-11');
INSERT INTO shows (banda, local, data) VALUES ('Hodus', 'Caruaru - Azulão', '2026-06-11');
INSERT INTO shows (banda, local, data) VALUES ('Joanatan Richard', 'Caruaru - Azulão', '2026-06-11');
INSERT INTO shows (banda, local, data) VALUES ('Trajano e os Traja Preta', 'Caruaru - Azulão', '2026-06-12');
INSERT INTO shows (banda, local, data) VALUES ('Alkymenia', 'Caruaru - Azulão', '2026-06-12');
INSERT INTO shows (banda, local, data) VALUES ('Devotos', 'Caruaru - Azulão', '2026-06-12');
INSERT INTO shows (banda, local, data) VALUES ('Nação Zumbi', 'Caruaru - Azulão', '2026-06-12');
INSERT INTO shows (banda, local, data) VALUES ('Riáh', 'Caruaru - Azulão', '2026-06-13');
INSERT INTO shows (banda, local, data) VALUES ('Jogo do Brasil + Azulão & Convidados', 'Caruaru - Azulão', '2026-06-13');
INSERT INTO shows (banda, local, data) VALUES ('Anastácia & Daniel Gonzaga', 'Caruaru - Azulão', '2026-06-13');
INSERT INTO shows (banda, local, data) VALUES ('Mestrinho', 'Caruaru - Azulão', '2026-06-13');
INSERT INTO shows (banda, local, data) VALUES ('Mazamorra', 'Caruaru - Azulão', '2026-06-18');
INSERT INTO shows (banda, local, data) VALUES ('Carcere Privado', 'Caruaru - Azulão', '2026-06-18');
INSERT INTO shows (banda, local, data) VALUES ('Visão Noturna', 'Caruaru - Azulão', '2026-06-18');
INSERT INTO shows (banda, local, data) VALUES ('Rapha Costa', 'Caruaru - Azulão', '2026-06-18');
INSERT INTO shows (banda, local, data) VALUES ('Los Cubanos', 'Caruaru - Azulão', '2026-06-19');
INSERT INTO shows (banda, local, data) VALUES ('Jogo do Brasil + Cascabulho', 'Caruaru - Azulão', '2026-06-19');
INSERT INTO shows (banda, local, data) VALUES ('Elvis', 'Caruaru - Azulão', '2026-06-19');
INSERT INTO shows (banda, local, data) VALUES ('Neiff', 'Caruaru - Azulão', '2026-06-19');
INSERT INTO shows (banda, local, data) VALUES ('Maestro Spok', 'Caruaru - Azulão', '2026-06-20');
INSERT INTO shows (banda, local, data) VALUES ('Maestro Mozart', 'Caruaru - Azulão', '2026-06-20');
INSERT INTO shows (banda, local, data) VALUES ('André Rio', 'Caruaru - Azulão', '2026-06-20');
INSERT INTO shows (banda, local, data) VALUES ('Chico César', 'Caruaru - Azulão', '2026-06-20');
INSERT INTO shows (banda, local, data) VALUES ('Driko', 'Caruaru - Azulão', '2026-06-23');
INSERT INTO shows (banda, local, data) VALUES ('Gerlane Lops', 'Caruaru - Azulão', '2026-06-23');
INSERT INTO shows (banda, local, data) VALUES ('Colibri Brasil', 'Caruaru - Azulão', '2026-06-23');
INSERT INTO shows (banda, local, data) VALUES ('Ylê Ayê', 'Caruaru - Azulão', '2026-06-23');
INSERT INTO shows (banda, local, data) VALUES ('Orquestra de Pifanos & Maestro Mozart Vieira', 'Caruaru - Pátio de Eventos', '2026-05-30');
INSERT INTO shows (banda, local, data) VALUES ('Elba Ramalho', 'Caruaru - Pátio de Eventos', '2026-05-30');
INSERT INTO shows (banda, local, data) VALUES ('Mari Fernandez', 'Caruaru - Pátio de Eventos', '2026-05-30');
INSERT INTO shows (banda, local, data) VALUES ('Solange Almeida', 'Caruaru - Pátio de Eventos', '2026-05-30');
INSERT INTO shows (banda, local, data) VALUES ('Assum Preto', 'Caruaru - Pátio de Eventos', '2026-05-31');
INSERT INTO shows (banda, local, data) VALUES ('Cavaleiros do Forró', 'Caruaru - Pátio de Eventos', '2026-05-31');
INSERT INTO shows (banda, local, data) VALUES ('Mastruz com Leite', 'Caruaru - Pátio de Eventos', '2026-05-31');
INSERT INTO shows (banda, local, data) VALUES ('Limão com Mel', 'Caruaru - Pátio de Eventos', '2026-05-31');
INSERT INTO shows (banda, local, data) VALUES ('Jonas Esticado', 'Caruaru - Pátio de Eventos', '2026-05-31');
INSERT INTO shows (banda, local, data) VALUES ('Albanita de Cássia', 'Caruaru - Pátio de Eventos', '2026-06-04');
INSERT INTO shows (banda, local, data) VALUES ('Willian Sanfona', 'Caruaru - Pátio de Eventos', '2026-06-04');
INSERT INTO shows (banda, local, data) VALUES ('Colo de Deus', 'Caruaru - Pátio de Eventos', '2026-06-04');
INSERT INTO shows (banda, local, data) VALUES ('Renan Cruz', 'Caruaru - Pátio de Eventos', '2026-06-05');
INSERT INTO shows (banda, local, data) VALUES ('Priscila Senna', 'Caruaru - Pátio de Eventos', '2026-06-05');
INSERT INTO shows (banda, local, data) VALUES ('A Vontade', 'Caruaru - Pátio de Eventos', '2026-06-05');
INSERT INTO shows (banda, local, data) VALUES ('Pablo', 'Caruaru - Pátio de Eventos', '2026-06-05');
INSERT INTO shows (banda, local, data) VALUES ('Nádia Maia', 'Caruaru - Pátio de Eventos', '2026-06-06');
INSERT INTO shows (banda, local, data) VALUES ('Raphaela Santos', 'Caruaru - Pátio de Eventos', '2026-06-06');
INSERT INTO shows (banda, local, data) VALUES ('Dorgival', 'Caruaru - Pátio de Eventos', '2026-06-06');
INSERT INTO shows (banda, local, data) VALUES ('Joelma', 'Caruaru - Pátio de Eventos', '2026-06-06');
INSERT INTO shows (banda, local, data) VALUES ('Belo', 'Caruaru - Pátio de Eventos', '2026-06-07');
INSERT INTO shows (banda, local, data) VALUES ('Nattan', 'Caruaru - Pátio de Eventos', '2026-06-07');
INSERT INTO shows (banda, local, data) VALUES ('Léo Santana', 'Caruaru - Pátio de Eventos', '2026-06-07');
INSERT INTO shows (banda, local, data) VALUES ('Thayse Dias', 'Caruaru - Pátio de Eventos', '2026-06-07');
INSERT INTO shows (banda, local, data) VALUES ('Roberto Carlos', 'Caruaru - Pátio de Eventos', '2026-06-12');
INSERT INTO shows (banda, local, data) VALUES ('Batista Lima', 'Caruaru - Pátio de Eventos', '2026-06-12');
INSERT INTO shows (banda, local, data) VALUES ('Zé Vaqueiro', 'Caruaru - Pátio de Eventos', '2026-06-13');
INSERT INTO shows (banda, local, data) VALUES ('Jogo do Brasil + Bell Marques', 'Caruaru - Pátio de Eventos', '2026-06-13');
INSERT INTO shows (banda, local, data) VALUES ('Alok', 'Caruaru - Pátio de Eventos', '2026-06-13');
INSERT INTO shows (banda, local, data) VALUES ('Guilherme Topado', 'Caruaru - Pátio de Eventos', '2026-06-13');
INSERT INTO shows (banda, local, data) VALUES ('Calango Aceso', 'Caruaru - Pátio de Eventos', '2026-06-14');
INSERT INTO shows (banda, local, data) VALUES ('Klever Lemos', 'Caruaru - Pátio de Eventos', '2026-06-14');
INSERT INTO shows (banda, local, data) VALUES ('Michele Andrade', 'Caruaru - Pátio de Eventos', '2026-06-14');
INSERT INTO shows (banda, local, data) VALUES ('Sorriso Maroto', 'Caruaru - Pátio de Eventos', '2026-06-14');
INSERT INTO shows (banda, local, data) VALUES ('Taty Girl', 'Caruaru - Pátio de Eventos', '2026-06-19');
INSERT INTO shows (banda, local, data) VALUES ('Sâmya Maia', 'Caruaru - Pátio de Eventos', '2026-06-19');
INSERT INTO shows (banda, local, data) VALUES ('Jogo do Brasil + Wesley Safadão', 'Caruaru - Pátio de Eventos', '2026-06-19');
INSERT INTO shows (banda, local, data) VALUES ('Eric Land', 'Caruaru - Pátio de Eventos', '2026-06-19');
INSERT INTO shows (banda, local, data) VALUES ('Mateus Santos', 'Caruaru - Pátio de Eventos', '2026-06-20');
INSERT INTO shows (banda, local, data) VALUES ('Léo Foguete', 'Caruaru - Pátio de Eventos', '2026-06-20');
INSERT INTO shows (banda, local, data) VALUES ('Lipe Lucena', 'Caruaru - Pátio de Eventos', '2026-06-20');
INSERT INTO shows (banda, local, data) VALUES ('Matheus e Kauan', 'Caruaru - Pátio de Eventos', '2026-06-20');
INSERT INTO shows (banda, local, data) VALUES ('Marquinhos Maraial', 'Caruaru - Pátio de Eventos', '2026-06-21');
INSERT INTO shows (banda, local, data) VALUES ('Silvânia e Berg', 'Caruaru - Pátio de Eventos', '2026-06-21');
INSERT INTO shows (banda, local, data) VALUES ('Luan Santana', 'Caruaru - Pátio de Eventos', '2026-06-21');
INSERT INTO shows (banda, local, data) VALUES ('Henry Freitas', 'Caruaru - Pátio de Eventos', '2026-06-21');
INSERT INTO shows (banda, local, data) VALUES ('Bell Marques', 'Gravatá - Pátio de Eventos', '2026-06-13');
INSERT INTO shows (banda, local, data) VALUES ('Raphaela Santos', 'Gravatá - Pátio de Eventos', '2026-06-13');
INSERT INTO shows (banda, local, data) VALUES ('Capim com Mel', 'Gravatá - Pátio de Eventos', '2026-06-13');
INSERT INTO shows (banda, local, data) VALUES ('Juciê', 'Gravatá - Pátio de Eventos', '2026-06-13');
INSERT INTO shows (banda, local, data) VALUES ('Jogo do Brasil', 'Gravatá - Pátio de Eventos', '2026-06-13');
INSERT INTO shows (banda, local, data) VALUES ('Murilo Huff', 'Gravatá - Pátio de Eventos', '2026-06-19');
INSERT INTO shows (banda, local, data) VALUES ('Priscila Senna', 'Gravatá - Pátio de Eventos', '2026-06-19');
INSERT INTO shows (banda, local, data) VALUES ('Eric Land', 'Gravatá - Pátio de Eventos', '2026-06-19');
INSERT INTO shows (banda, local, data) VALUES ('Wallas Arrais', 'Gravatá - Pátio de Eventos', '2026-06-19');
INSERT INTO shows (banda, local, data) VALUES ('Jogo do Brasil', 'Gravatá - Pátio de Eventos', '2026-06-19');
INSERT INTO shows (banda, local, data) VALUES ('Falamansa', 'Gravatá - Pátio de Eventos', '2026-06-20');
INSERT INTO shows (banda, local, data) VALUES ('PV Calado', 'Gravatá - Pátio de Eventos', '2026-06-20');
INSERT INTO shows (banda, local, data) VALUES ('Baby Som', 'Gravatá - Pátio de Eventos', '2026-06-20');
INSERT INTO shows (banda, local, data) VALUES ('Danillo Henrique', 'Gravatá - Pátio de Eventos', '2026-06-20');
INSERT INTO shows (banda, local, data) VALUES ('Natanzinho Lima', 'Gravatá - Pátio de Eventos', '2026-06-21');
INSERT INTO shows (banda, local, data) VALUES ('Taty Girl', 'Gravatá - Pátio de Eventos', '2026-06-21');
INSERT INTO shows (banda, local, data) VALUES ('Lipe Lucena', 'Gravatá - Pátio de Eventos', '2026-06-21');
INSERT INTO shows (banda, local, data) VALUES ('Maurício Meneses', 'Gravatá - Pátio de Eventos', '2026-06-21');
INSERT INTO shows (banda, local, data) VALUES ('Xand Avião', 'Gravatá - Pátio de Eventos', '2026-06-22');
INSERT INTO shows (banda, local, data) VALUES ('Ávine Vinny', 'Gravatá - Pátio de Eventos', '2026-06-22');
INSERT INTO shows (banda, local, data) VALUES ('Brasas do Forró', 'Gravatá - Pátio de Eventos', '2026-06-22');
INSERT INTO shows (banda, local, data) VALUES ('Edu Lira', 'Gravatá - Pátio de Eventos', '2026-06-22');
INSERT INTO shows (banda, local, data) VALUES ('Wesley Safadão', 'Gravatá - Pátio de Eventos', '2026-06-23');
INSERT INTO shows (banda, local, data) VALUES ('Cláudio Ney e Juliana', 'Gravatá - Pátio de Eventos', '2026-06-23');
INSERT INTO shows (banda, local, data) VALUES ('Paula Mattos', 'Gravatá - Pátio de Eventos', '2026-06-23');
INSERT INTO shows (banda, local, data) VALUES ('Deb Lima', 'Gravatá - Pátio de Eventos', '2026-06-23');
INSERT INTO shows (banda, local, data) VALUES ('Myllena Dantas', 'Gravatá - Pátio de Eventos', '2026-06-23');
INSERT INTO shows (banda, local, data) VALUES ('Xand Avião', 'Carpina - Palco Principal', '2026-06-23');
INSERT INTO shows (banda, local, data) VALUES ('Leonardo', 'Carpina - Palco Principal', '2026-06-23');
INSERT INTO shows (banda, local, data) VALUES ('Alok', 'Carpina - Palco Principal', '2026-06-23');
INSERT INTO shows (banda, local, data) VALUES ('Gabriel Vaqueiro', 'Carpina - Palco Principal', '2026-06-23');
INSERT INTO shows (banda, local, data) VALUES ('Wesley Safadão', 'Carpina - Palco Principal', '2026-06-24');
INSERT INTO shows (banda, local, data) VALUES ('Gusttavo Lima', 'Carpina - Palco Principal', '2026-06-24');
INSERT INTO shows (banda, local, data) VALUES ('Eric Land', 'Carpina - Palco Principal', '2026-06-24');
INSERT INTO shows (banda, local, data) VALUES ('Zé Elias', 'Carpina - Palco Principal', '2026-06-24');
INSERT INTO shows (banda, local, data) VALUES ('Deivinho Sanfoneiro', 'Carpina - Palco Principal', '2026-06-24');
INSERT INTO shows (banda, local, data) VALUES ('Nattan', 'Carpina - Palco Principal', '2026-06-25');
INSERT INTO shows (banda, local, data) VALUES ('Natanzinho Lima', 'Carpina - Palco Principal', '2026-06-25');
INSERT INTO shows (banda, local, data) VALUES ('Rey Vaqueiro', 'Carpina - Palco Principal', '2026-06-25');
INSERT INTO shows (banda, local, data) VALUES ('Patrick Costa', 'Carpina - Palco Principal', '2026-06-25');
INSERT INTO shows (banda, local, data) VALUES ('João Gomes', 'Carpina - Palco Principal', '2026-06-26');
INSERT INTO shows (banda, local, data) VALUES ('Pablo', 'Carpina - Palco Principal', '2026-06-26');
INSERT INTO shows (banda, local, data) VALUES ('Henry Freitas', 'Carpina - Palco Principal', '2026-06-26');
INSERT INTO shows (banda, local, data) VALUES ('Juarez', 'Carpina - Palco Principal', '2026-06-26');
INSERT INTO shows (banda, local, data) VALUES ('Raphaela Santos', 'Carpina - Palco Principal', '2026-06-27');
INSERT INTO shows (banda, local, data) VALUES ('Pricila Senna', 'Carpina - Palco Principal', '2026-06-27');
INSERT INTO shows (banda, local, data) VALUES ('César Menotti & Fabiano', 'Carpina - Palco Principal', '2026-06-27');
INSERT INTO shows (banda, local, data) VALUES ('Ávine Vinny', 'Carpina - Palco Principal', '2026-06-27');
INSERT INTO shows (banda, local, data) VALUES ('Juara Marques', 'Vicência - Palco Principal', '2026-06-23');
INSERT INTO shows (banda, local, data) VALUES ('Anjos do Forró', 'Vicência - Palco Principal', '2026-06-23');
INSERT INTO shows (banda, local, data) VALUES ('Tayara Andreza', 'Vicência - Palco Principal', '2026-06-28');
INSERT INTO shows (banda, local, data) VALUES ('Rogério Som', 'Vicência - Palco Principal', '2026-06-28');
INSERT INTO shows (banda, local, data) VALUES ('Tarcísio do Acordeon', 'Vicência - Palco Principal', '2026-06-29');
INSERT INTO shows (banda, local, data) VALUES ('Vilões do Forró', 'Vicência - Palco Principal', '2026-06-29');
INSERT INTO shows (banda, local, data) VALUES ('Yasmin Sensação', 'Vicência - Palco Principal', '2026-06-30');
INSERT INTO shows (banda, local, data) VALUES ('Forró Tropikália', 'Vicência - Palco Principal', '2026-06-30');
INSERT INTO shows (banda, local, data) VALUES ('Trio Magia do Sol (Itinerante)', 'Recife - Rio Branco', '2026-06-14');
INSERT INTO shows (banda, local, data) VALUES ('Zé Tamanquinho - Lucas dos Prazeres', 'Recife - Rio Branco', '2026-06-14');
INSERT INTO shows (banda, local, data) VALUES ('Família Salustiano', 'Recife - Rio Branco', '2026-06-14');
INSERT INTO shows (banda, local, data) VALUES ('Salatiel de Camarão', 'Recife - Rio Branco', '2026-06-14');
INSERT INTO shows (banda, local, data) VALUES ('Roberto Cruz', 'Recife - Rio Branco', '2026-06-14');
INSERT INTO shows (banda, local, data) VALUES ('Azulinho', 'Recife - Rio Branco', '2026-06-14');
INSERT INTO shows (banda, local, data) VALUES ('Trio Pérola Negra (Itinerante)', 'Recife - Rio Branco', '2026-06-17');
INSERT INTO shows (banda, local, data) VALUES ('Trio Arranca Rabo', 'Recife - Rio Branco', '2026-06-17');
INSERT INTO shows (banda, local, data) VALUES ('Trio Mexe Mexe', 'Recife - Rio Branco', '2026-06-17');
INSERT INTO shows (banda, local, data) VALUES ('Rabecado', 'Recife - Rio Branco', '2026-06-17');
INSERT INTO shows (banda, local, data) VALUES ('Lucinha Guerra', 'Recife - Rio Branco', '2026-06-17');
INSERT INTO shows (banda, local, data) VALUES ('Trio Palha de Milho (Itinerante)', 'Recife - Rio Branco', '2026-06-18');
INSERT INTO shows (banda, local, data) VALUES ('Trio Culé de Xá', 'Recife - Rio Branco', '2026-06-18');
INSERT INTO shows (banda, local, data) VALUES ('Kelly Rosa', 'Recife - Rio Branco', '2026-06-18');
INSERT INTO shows (banda, local, data) VALUES ('Aracílio Araújo', 'Recife - Rio Branco', '2026-06-18');
INSERT INTO shows (banda, local, data) VALUES ('Pandeirada - Miguel Marinho', 'Recife - Rio Branco', '2026-06-18');
INSERT INTO shows (banda, local, data) VALUES ('Trio Nordeste Show (Itinerante)', 'Recife - Rio Branco', '2026-06-19');
INSERT INTO shows (banda, local, data) VALUES ('Trio Sanfona do Povo', 'Recife - Rio Branco', '2026-06-19');
INSERT INTO shows (banda, local, data) VALUES ('Trio Xodó Maior', 'Recife - Rio Branco', '2026-06-19');
INSERT INTO shows (banda, local, data) VALUES ('Trio 100% Mulher', 'Recife - Rio Branco', '2026-06-19');
INSERT INTO shows (banda, local, data) VALUES ('Márcia Pequeno', 'Recife - Rio Branco', '2026-06-19');
INSERT INTO shows (banda, local, data) VALUES ('Pausa para jogo do Brasil', 'Recife - Rio Branco', '2026-06-19');
INSERT INTO shows (banda, local, data) VALUES ('Regente Joaquim', 'Recife - Rio Branco', '2026-06-19');
INSERT INTO shows (banda, local, data) VALUES ('Trio Astral (Itinerante)', 'Recife - Rio Branco', '2026-06-20');
INSERT INTO shows (banda, local, data) VALUES ('Balé Popular do Recife', 'Recife - Rio Branco', '2026-06-20');
INSERT INTO shows (banda, local, data) VALUES ('Cantata Junina', 'Recife - Rio Branco', '2026-06-20');
INSERT INTO shows (banda, local, data) VALUES ('Balancê Poético', 'Recife - Rio Branco', '2026-06-20');
INSERT INTO shows (banda, local, data) VALUES ('Mônica Feijó', 'Recife - Rio Branco', '2026-06-20');
INSERT INTO shows (banda, local, data) VALUES ('Laís Senna', 'Recife - Rio Branco', '2026-06-20');
INSERT INTO shows (banda, local, data) VALUES ('Luciano Magno', 'Recife - Rio Branco', '2026-06-20');
INSERT INTO shows (banda, local, data) VALUES ('Forró Chão de Barro (Itinerante)', 'Recife - Rio Branco', '2026-06-21');
INSERT INTO shows (banda, local, data) VALUES ('Cavalo Marinho Boi Pintado', 'Recife - Rio Branco', '2026-06-21');
INSERT INTO shows (banda, local, data) VALUES ('Quadrilha Junina Lumiar', 'Recife - Rio Branco', '2026-06-21');
INSERT INTO shows (banda, local, data) VALUES ('Coco dos Pretos', 'Recife - Rio Branco', '2026-06-21');
INSERT INTO shows (banda, local, data) VALUES ('Adiel Luna', 'Recife - Rio Branco', '2026-06-21');
INSERT INTO shows (banda, local, data) VALUES ('Luan Nascimento', 'Recife - Rio Branco', '2026-06-21');
INSERT INTO shows (banda, local, data) VALUES ('Walkyria Mendes', 'Recife - Rio Branco', '2026-06-21');
INSERT INTO shows (banda, local, data) VALUES ('Trio Forró Luado (Itinerante)', 'Recife - Rio Branco', '2026-06-22');
INSERT INTO shows (banda, local, data) VALUES ('Candeeiro Encantado Forró', 'Recife - Rio Branco', '2026-06-22');
INSERT INTO shows (banda, local, data) VALUES ('Remanso do Forró', 'Recife - Rio Branco', '2026-06-22');
INSERT INTO shows (banda, local, data) VALUES ('Luciano Ferraz', 'Recife - Rio Branco', '2026-06-22');
INSERT INTO shows (banda, local, data) VALUES ('André Lins', 'Recife - Rio Branco', '2026-06-22');
INSERT INTO shows (banda, local, data) VALUES ('Trio Forró Brasileiro (Itinerante)', 'Recife - Rio Branco', '2026-06-23');
INSERT INTO shows (banda, local, data) VALUES ('Quadrilha Junina Origem Nordestina', 'Recife - Rio Branco', '2026-06-23');
INSERT INTO shows (banda, local, data) VALUES ('Trio Forró das Cumádi', 'Recife - Rio Branco', '2026-06-23');
INSERT INTO shows (banda, local, data) VALUES ('Mestre Galo Preto', 'Recife - Rio Branco', '2026-06-23');
INSERT INTO shows (banda, local, data) VALUES ('Mevinha Queiroga', 'Recife - Rio Branco', '2026-06-23');
INSERT INTO shows (banda, local, data) VALUES ('Ava Guimarães', 'Recife - Rio Branco', '2026-06-23');
INSERT INTO shows (banda, local, data) VALUES ('Sarah Leandro', 'Recife - Rio Branco', '2026-06-23');
INSERT INTO shows (banda, local, data) VALUES ('Larissa Lisboa', 'Recife - Rio Branco', '2026-06-23');
INSERT INTO shows (banda, local, data) VALUES ('Isadora Melo', 'Recife - Rio Branco', '2026-06-23');
INSERT INTO shows (banda, local, data) VALUES ('Trio Nilza Ângela', 'Recife - Rio Branco', '2026-06-24');
INSERT INTO shows (banda, local, data) VALUES ('Quadrilha Junina Zabumba', 'Recife - Rio Branco', '2026-06-24');
INSERT INTO shows (banda, local, data) VALUES ('Cia de Dança Perna de Palco', 'Recife - Rio Branco', '2026-06-24');
INSERT INTO shows (banda, local, data) VALUES ('Grupo Chinelo de Iaiá', 'Recife - Rio Branco', '2026-06-24');
INSERT INTO shows (banda, local, data) VALUES ('Pablitto', 'Recife - Rio Branco', '2026-06-24');
INSERT INTO shows (banda, local, data) VALUES ('Pausa para jogo do Brasil', 'Recife - Rio Branco', '2026-06-24');
INSERT INTO shows (banda, local, data) VALUES ('Pecinho Amorim', 'Recife - Rio Branco', '2026-06-24');
INSERT INTO shows (banda, local, data) VALUES ('Trio Harmonia (Itinerante)', 'Recife - Rio Branco', '2026-06-26');
INSERT INTO shows (banda, local, data) VALUES ('Coco do Rosário', 'Recife - Rio Branco', '2026-06-26');
INSERT INTO shows (banda, local, data) VALUES ('Mestre Bi e a Ciranda Bela Rosa', 'Recife - Rio Branco', '2026-06-26');
INSERT INTO shows (banda, local, data) VALUES ('Chiló Trio', 'Recife - Rio Branco', '2026-06-26');
INSERT INTO shows (banda, local, data) VALUES ('Felipe Costta', 'Recife - Rio Branco', '2026-06-26');
INSERT INTO shows (banda, local, data) VALUES ('César Amaral', 'Recife - Rio Branco', '2026-06-26');
INSERT INTO shows (banda, local, data) VALUES ('Clara Sobral', 'Recife - Rio Branco', '2026-06-26');
INSERT INTO shows (banda, local, data) VALUES ('Trio Tempero do Forró', 'Recife - Rio Branco', '2026-06-27');
INSERT INTO shows (banda, local, data) VALUES ('Quadrilha Junina Dona Matuta', 'Recife - Rio Branco', '2026-06-27');
INSERT INTO shows (banda, local, data) VALUES ('Balé Deveras', 'Recife - Rio Branco', '2026-06-27');
INSERT INTO shows (banda, local, data) VALUES ('Coco do Juremá', 'Recife - Rio Branco', '2026-06-27');
INSERT INTO shows (banda, local, data) VALUES ('Reinivaldo Pinheiro', 'Recife - Rio Branco', '2026-06-27');
INSERT INTO shows (banda, local, data) VALUES ('Alexandre Rodrigues - Baile de Pife', 'Recife - Rio Branco', '2026-06-27');
INSERT INTO shows (banda, local, data) VALUES ('Nailson Vieira', 'Recife - Rio Branco', '2026-06-27');
INSERT INTO shows (banda, local, data) VALUES ('Banda Coruja e Seus Tangarás', 'Recife - Rio Branco', '2026-06-27');
INSERT INTO shows (banda, local, data) VALUES ('Trio Forró Bombado (Itinerante)', 'Recife - Rio Branco', '2026-06-28');
INSERT INTO shows (banda, local, data) VALUES ('Cia Trapiá de Dança', 'Recife - Rio Branco', '2026-06-28');
INSERT INTO shows (banda, local, data) VALUES ('Quadrilha Raio de Sol', 'Recife - Rio Branco', '2026-06-28');
INSERT INTO shows (banda, local, data) VALUES ('Coco de Umbigada', 'Recife - Rio Branco', '2026-06-28');
INSERT INTO shows (banda, local, data) VALUES ('Ângelo Gabriel', 'Recife - Rio Branco', '2026-06-28');
INSERT INTO shows (banda, local, data) VALUES ('Terezinha do Acordeon', 'Recife - Rio Branco', '2026-06-28');
INSERT INTO shows (banda, local, data) VALUES ('Juba', 'Recife - Rio Branco', '2026-06-28');
INSERT INTO shows (banda, local, data) VALUES ('Banda Sinfônica do Recife (Part. Anastácia e Juliana Linhares)', 'Recife - Sítio Trindade (Palco Principal)', '2026-06-18');
INSERT INTO shows (banda, local, data) VALUES ('Santanna O Cantador', 'Recife - Sítio Trindade (Palco Principal)', '2026-06-18');
INSERT INTO shows (banda, local, data) VALUES ('Ciranda Dengosa', 'Recife - Sítio Trindade (Palco Principal)', '2026-06-19');
INSERT INTO shows (banda, local, data) VALUES ('Caju e Castanha', 'Recife - Sítio Trindade (Palco Principal)', '2026-06-19');
INSERT INTO shows (banda, local, data) VALUES ('Pausa para jogo do Brasil', 'Recife - Sítio Trindade (Palco Principal)', '2026-06-19');
INSERT INTO shows (banda, local, data) VALUES ('Geraldo Azevedo', 'Recife - Sítio Trindade (Palco Principal)', '2026-06-19');
INSERT INTO shows (banda, local, data) VALUES ('Forró do Muído', 'Recife - Sítio Trindade (Palco Principal)', '2026-06-19');
INSERT INTO shows (banda, local, data) VALUES ('Zelyto Madeira', 'Recife - Sítio Trindade (Sala de Reboco)', '2026-06-19');
INSERT INTO shows (banda, local, data) VALUES ('Anchieta Dali', 'Recife - Sítio Trindade (Sala de Reboco)', '2026-06-19');
INSERT INTO shows (banda, local, data) VALUES ('Forró Sensação', 'Recife - Sítio Trindade (Sala de Reboco)', '2026-06-19');
INSERT INTO shows (banda, local, data) VALUES ('Pausa para jogo do Brasil', 'Recife - Sítio Trindade (Sala de Reboco)', '2026-06-19');
INSERT INTO shows (banda, local, data) VALUES ('Cydia Lima', 'Recife - Sítio Trindade (Sala de Reboco)', '2026-06-19');
INSERT INTO shows (banda, local, data) VALUES ('Rodrigo Raposo', 'Recife - Sítio Trindade (Sala de Reboco)', '2026-06-19');
INSERT INTO shows (banda, local, data) VALUES ('Boi Faceiro', 'Recife - Sítio Trindade (Palco Principal)', '2026-06-20');
INSERT INTO shows (banda, local, data) VALUES ('Bia Marinho', 'Recife - Sítio Trindade (Palco Principal)', '2026-06-20');
INSERT INTO shows (banda, local, data) VALUES ('Anastácia', 'Recife - Sítio Trindade (Palco Principal)', '2026-06-20');
INSERT INTO shows (banda, local, data) VALUES ('Fim de Feira', 'Recife - Sítio Trindade (Palco Principal)', '2026-06-20');
INSERT INTO shows (banda, local, data) VALUES ('Vinil Gonzagueira', 'Recife - Sítio Trindade (Sala de Reboco)', '2026-06-20');
INSERT INTO shows (banda, local, data) VALUES ('Joaozinho de Exu', 'Recife - Sítio Trindade (Sala de Reboco)', '2026-06-20');
INSERT INTO shows (banda, local, data) VALUES ('Israel Filho', 'Recife - Sítio Trindade (Sala de Reboco)', '2026-06-20');
INSERT INTO shows (banda, local, data) VALUES ('Grupo Mazuca da Quixaba', 'Recife - Sítio Trindade (Palco Principal)', '2026-06-21');
INSERT INTO shows (banda, local, data) VALUES ('Rogério Rangel', 'Recife - Sítio Trindade (Palco Principal)', '2026-06-21');
INSERT INTO shows (banda, local, data) VALUES ('Banda de Pau e Corda', 'Recife - Sítio Trindade (Palco Principal)', '2026-06-21');
INSERT INTO shows (banda, local, data) VALUES ('Novinho da Paraíba', 'Recife - Sítio Trindade (Palco Principal)', '2026-06-21');
INSERT INTO shows (banda, local, data) VALUES ('Geraldinho Lins', 'Recife - Sítio Trindade (Palco Principal)', '2026-06-21');
INSERT INTO shows (banda, local, data) VALUES ('João Lacerda', 'Recife - Sítio Trindade (Sala de Reboco)', '2026-06-21');
INSERT INTO shows (banda, local, data) VALUES ('Xaxado do Egídio', 'Recife - Sítio Trindade (Palco Principal)', '2026-06-22');
INSERT INTO shows (banda, local, data) VALUES ('Fabiana Pimentinha', 'Recife - Sítio Trindade (Palco Principal)', '2026-06-22');
INSERT INTO shows (banda, local, data) VALUES ('Quinteto Violado', 'Recife - Sítio Trindade (Palco Principal)', '2026-06-22');
INSERT INTO shows (banda, local, data) VALUES ('Maciel Salu (Participação Madu)', 'Recife - Sítio Trindade (Palco Principal)', '2026-06-22');
INSERT INTO shows (banda, local, data) VALUES ('Capim com Mel', 'Recife - Sítio Trindade (Palco Principal)', '2026-06-22');
INSERT INTO shows (banda, local, data) VALUES ('Marinho do Recife', 'Recife - Sítio Trindade (Sala de Reboco)', '2026-06-22');
INSERT INTO shows (banda, local, data) VALUES ('Aleixo dos Oito Baixos', 'Recife - Sítio Trindade (Sala de Reboco)', '2026-06-22');
INSERT INTO shows (banda, local, data) VALUES ('Paulo Matricó', 'Recife - Sítio Trindade (Sala de Reboco)', '2026-06-22');
INSERT INTO shows (banda, local, data) VALUES ('Tony Melo', 'Recife - Sítio Trindade (Sala de Reboco)', '2026-06-22');
INSERT INTO shows (banda, local, data) VALUES ('Cylene Araújo', 'Recife - Sítio Trindade (Sala de Reboco)', '2026-06-22');
INSERT INTO shows (banda, local, data) VALUES ('Quadrilha Junina Mirim Matutinho Dançante', 'Recife - Sítio Trindade (Pavilhão Infantil)', '2026-06-23');
INSERT INTO shows (banda, local, data) VALUES ('Cigarra Kika - Kelly Benevides', 'Recife - Sítio Trindade (Pavilhão Infantil)', '2026-06-23');
INSERT INTO shows (banda, local, data) VALUES ('Joanah Flor - Pernambucaninhus', 'Recife - Sítio Trindade (Pavilhão Infantil)', '2026-06-23');
INSERT INTO shows (banda, local, data) VALUES ('Mari Bigio', 'Recife - Sítio Trindade (Pavilhão Infantil)', '2026-06-23');
INSERT INTO shows (banda, local, data) VALUES ('Mestre Anderson Miguel e a Ciranda Raiz', 'Recife - Sítio Trindade (Palco Principal)', '2026-06-23');
INSERT INTO shows (banda, local, data) VALUES ('Terezinha do Acordeon', 'Recife - Sítio Trindade (Palco Principal)', '2026-06-23');
INSERT INTO shows (banda, local, data) VALUES ('Irah Caldeira', 'Recife - Sítio Trindade (Palco Principal)', '2026-06-23');
INSERT INTO shows (banda, local, data) VALUES ('Benil', 'Recife - Sítio Trindade (Palco Principal)', '2026-06-23');
INSERT INTO shows (banda, local, data) VALUES ('Petrúcio Amorim', 'Recife - Sítio Trindade (Palco Principal)', '2026-06-23');
INSERT INTO shows (banda, local, data) VALUES ('Diego Cabral', 'Recife - Sítio Trindade (Palco Principal)', '2026-06-23');
INSERT INTO shows (banda, local, data) VALUES ('Fredy e Mary', 'Recife - Sítio Trindade (Sala de Reboco)', '2026-06-23');
INSERT INTO shows (banda, local, data) VALUES ('Pecinho', 'Recife - Sítio Trindade (Sala de Reboco)', '2026-06-23');
INSERT INTO shows (banda, local, data) VALUES ('Chico Balla', 'Recife - Sítio Trindade (Sala de Reboco)', '2026-06-23');
INSERT INTO shows (banda, local, data) VALUES ('Bete de Castro', 'Recife - Sítio Trindade (Sala de Reboco)', '2026-06-23');
INSERT INTO shows (banda, local, data) VALUES ('Savinho do Acordeon', 'Recife - Sítio Trindade (Sala de Reboco)', '2026-06-23');
INSERT INTO shows (banda, local, data) VALUES ('Quadrilha Junina Brincants Show', 'Recife - Sítio Trindade (Pavilhão Infantil)', '2026-06-24');
INSERT INTO shows (banda, local, data) VALUES ('Fada Magrinha', 'Recife - Sítio Trindade (Pavilhão Infantil)', '2026-06-24');
INSERT INTO shows (banda, local, data) VALUES ('Mini Rock', 'Recife - Sítio Trindade (Pavilhão Infantil)', '2026-06-24');
INSERT INTO shows (banda, local, data) VALUES ('Jangadinha - Ylana Queiroga', 'Recife - Sítio Trindade (Pavilhão Infantil)', '2026-06-24');
INSERT INTO shows (banda, local, data) VALUES ('Beto Hortis', 'Recife - Sítio Trindade (Palco Principal)', '2026-06-24');
INSERT INTO shows (banda, local, data) VALUES ('Pausa para jogo do Brasil', 'Recife - Sítio Trindade (Palco Principal)', '2026-06-24');
INSERT INTO shows (banda, local, data) VALUES ('Cristina Amaral', 'Recife - Sítio Trindade (Palco Principal)', '2026-06-24');
INSERT INTO shows (banda, local, data) VALUES ('Joyce Alane', 'Recife - Sítio Trindade (Palco Principal)', '2026-06-24');
INSERT INTO shows (banda, local, data) VALUES ('Ari de Arimatéia', 'Recife - Sítio Trindade (Sala de Reboco)', '2026-06-24');
INSERT INTO shows (banda, local, data) VALUES ('Seu Januário', 'Recife - Sítio Trindade (Sala de Reboco)', '2026-06-24');
INSERT INTO shows (banda, local, data) VALUES ('Coco de Mãe Preta', 'Recife - Sítio Trindade (Palco Principal)', '2026-06-26');
INSERT INTO shows (banda, local, data) VALUES ('Assisão', 'Recife - Sítio Trindade (Palco Principal)', '2026-06-26');
INSERT INTO shows (banda, local, data) VALUES ('Silvério', 'Recife - Sítio Trindade (Palco Principal)', '2026-06-26');
INSERT INTO shows (banda, local, data) VALUES ('Forró na Caixa', 'Recife - Sítio Trindade (Palco Principal)', '2026-06-26');
INSERT INTO shows (banda, local, data) VALUES ('Elba Ramalho', 'Recife - Sítio Trindade (Palco Principal)', '2026-06-26');
INSERT INTO shows (banda, local, data) VALUES ('Galeguinho de Gravatá', 'Recife - Sítio Trindade (Sala de Reboco)', '2026-06-26');
INSERT INTO shows (banda, local, data) VALUES ('Muniz do Arrasta-pé', 'Recife - Sítio Trindade (Sala de Reboco)', '2026-06-26');
INSERT INTO shows (banda, local, data) VALUES ('Carlos Filho', 'Recife - Sítio Trindade (Sala de Reboco)', '2026-06-26');
INSERT INTO shows (banda, local, data) VALUES ('André Macambira', 'Recife - Sítio Trindade (Sala de Reboco)', '2026-06-26');
INSERT INTO shows (banda, local, data) VALUES ('Aécio dos Oito Baixos', 'Recife - Sítio Trindade (Sala de Reboco)', '2026-06-26');
INSERT INTO shows (banda, local, data) VALUES ('Quadrilha Raio de Sol Mirim', 'Recife - Sítio Trindade (Pavilhão Infantil)', '2026-06-27');
INSERT INTO shows (banda, local, data) VALUES ('Tio Bruninho', 'Recife - Sítio Trindade (Pavilhão Infantil)', '2026-06-27');
INSERT INTO shows (banda, local, data) VALUES ('Bailinho Kids', 'Recife - Sítio Trindade (Pavilhão Infantil)', '2026-06-27');
INSERT INTO shows (banda, local, data) VALUES ('A Bandinha', 'Recife - Sítio Trindade (Pavilhão Infantil)', '2026-06-27');
INSERT INTO shows (banda, local, data) VALUES ('As Netas de Selma do Coco', 'Recife - Sítio Trindade (Palco Principal)', '2026-06-27');
INSERT INTO shows (banda, local, data) VALUES ('Lia de Itamaracá', 'Recife - Sítio Trindade (Palco Principal)', '2026-06-27');
INSERT INTO shows (banda, local, data) VALUES ('Liv Moraes', 'Recife - Sítio Trindade (Palco Principal)', '2026-06-27');
INSERT INTO shows (banda, local, data) VALUES ('Josildo Sá', 'Recife - Sítio Trindade (Palco Principal)', '2026-06-27');
INSERT INTO shows (banda, local, data) VALUES ('Jorge de Altinho', 'Recife - Sítio Trindade (Palco Principal)', '2026-06-27');
INSERT INTO shows (banda, local, data) VALUES ('Aluízio do Acordeon e Banda', 'Recife - Sítio Trindade (Sala de Reboco)', '2026-06-27');
INSERT INTO shows (banda, local, data) VALUES ('Dirceu Melo e Forró Rabeca', 'Recife - Sítio Trindade (Sala de Reboco)', '2026-06-27');
INSERT INTO shows (banda, local, data) VALUES ('Daniel Bento', 'Recife - Sítio Trindade (Sala de Reboco)', '2026-06-27');
INSERT INTO shows (banda, local, data) VALUES ('Patrícia Cruz', 'Recife - Sítio Trindade (Sala de Reboco)', '2026-06-27');
INSERT INTO shows (banda, local, data) VALUES ('Quadrilha Mirim Evolução', 'Recife - Sítio Trindade (Pavilhão Infantil)', '2026-06-28');
INSERT INTO shows (banda, local, data) VALUES ('Bandinha Circense', 'Recife - Sítio Trindade (Pavilhão Infantil)', '2026-06-28');
INSERT INTO shows (banda, local, data) VALUES ('Carol Levy', 'Recife - Sítio Trindade (Pavilhão Infantil)', '2026-06-28');
INSERT INTO shows (banda, local, data) VALUES ('Festival de Quadrilhas Liquajur', 'Recife - Sítio Trindade (Pavilhão Infantil)', '2026-06-28');
INSERT INTO shows (banda, local, data) VALUES ('Pernambucaneando', 'Recife - Sítio Trindade (Palco Principal)', '2026-06-28');
INSERT INTO shows (banda, local, data) VALUES ('Mestre Gennaro', 'Recife - Sítio Trindade (Palco Principal)', '2026-06-28');
INSERT INTO shows (banda, local, data) VALUES ('Nádia Maia', 'Recife - Sítio Trindade (Palco Principal)', '2026-06-28');
INSERT INTO shows (banda, local, data) VALUES ('Nando Cordel', 'Recife - Sítio Trindade (Palco Principal)', '2026-06-28');
INSERT INTO shows (banda, local, data) VALUES ('Maciel Melo', 'Recife - Sítio Trindade (Palco Principal)', '2026-06-28');
INSERT INTO shows (banda, local, data) VALUES ('Ceiça Moreno', 'Recife - Sítio Trindade (Sala de Reboco)', '2026-06-28');
INSERT INTO shows (banda, local, data) VALUES ('Quadrilha Junina Tradição Nordestina', 'Recife - Pátio de São Pedro', '2026-06-27');
INSERT INTO shows (banda, local, data) VALUES ('Ciranda Imperial', 'Recife - Pátio de São Pedro', '2026-06-27');
INSERT INTO shows (banda, local, data) VALUES ('Mazinho de Arcoverde', 'Recife - Pátio de São Pedro', '2026-06-27');
INSERT INTO shows (banda, local, data) VALUES ('Claudio Rabeca', 'Recife - Pátio de São Pedro', '2026-06-27');
INSERT INTO shows (banda, local, data) VALUES ('Zé Brown', 'Recife - Pátio de São Pedro', '2026-06-27');
INSERT INTO shows (banda, local, data) VALUES ('Marcela Souza', 'Recife - Pátio de São Pedro', '2026-06-28');
INSERT INTO shows (banda, local, data) VALUES ('Sambada Família Salustiano', 'Recife - Pátio de São Pedro', '2026-06-28');
INSERT INTO shows (banda, local, data) VALUES ('Poli', 'Recife - Pátio de São Pedro', '2026-06-28');
INSERT INTO shows (banda, local, data) VALUES ('Mestre Ambrósio', 'Recife - Pátio de São Pedro', '2026-06-28');
INSERT INTO shows (banda, local, data) VALUES ('Boi Mimoso da Bomba Hemetério', 'Recife - Pátio de São Pedro', '2026-06-29');
INSERT INTO shows (banda, local, data) VALUES ('Coco de Mulheres', 'Recife - Pátio de São Pedro', '2026-06-29');
INSERT INTO shows (banda, local, data) VALUES ('Caju e Castanha', 'Recife - Pátio de São Pedro', '2026-06-29');
INSERT INTO shows (banda, local, data) VALUES ('Siba', 'Recife - Pátio de São Pedro', '2026-06-29');
INSERT INTO shows (banda, local, data) VALUES ('Nerilson Buscapé', 'Caruaru - Casa Rosa', '2026-05-30');
INSERT INTO shows (banda, local, data) VALUES ('Dayse Rosa', 'Caruaru - Casa Rosa', '2026-05-30');
INSERT INTO shows (banda, local, data) VALUES ('Banda Seu Januário', 'Caruaru - Casa Rosa', '2026-05-30');
INSERT INTO shows (banda, local, data) VALUES ('Capital Nordestina', 'Caruaru - Casa Rosa', '2026-05-31');
INSERT INTO shows (banda, local, data) VALUES ('Lucas Silva', 'Caruaru - Casa Rosa', '2026-05-31');
INSERT INTO shows (banda, local, data) VALUES ('Edilza Aires', 'Caruaru - Casa Rosa', '2026-05-31');
INSERT INTO shows (banda, local, data) VALUES ('Nego do Acordeon', 'Caruaru - Casa Rosa', '2026-06-06');
INSERT INTO shows (banda, local, data) VALUES ('Carlinhos Nova', 'Caruaru - Casa Rosa', '2026-06-06');
INSERT INTO shows (banda, local, data) VALUES ('Walmir Silva', 'Caruaru - Casa Rosa', '2026-06-06');
INSERT INTO shows (banda, local, data) VALUES ('Alberto Zarfan', 'Caruaru - Casa Rosa', '2026-06-07');
INSERT INTO shows (banda, local, data) VALUES ('Maurício Ramalho', 'Caruaru - Casa Rosa', '2026-06-07');
INSERT INTO shows (banda, local, data) VALUES ('Pecinho Amorim', 'Caruaru - Casa Rosa', '2026-06-07');
INSERT INTO shows (banda, local, data) VALUES ('Jô Caruaru', 'Caruaru - Casa Rosa', '2026-06-12');
INSERT INTO shows (banda, local, data) VALUES ('Samara Costa', 'Caruaru - Casa Rosa', '2026-06-12');
INSERT INTO shows (banda, local, data) VALUES ('Vyni Amorim', 'Caruaru - Casa Rosa', '2026-06-12');
INSERT INTO shows (banda, local, data) VALUES ('Derso Luis', 'Caruaru - Casa Rosa', '2026-06-13');
INSERT INTO shows (banda, local, data) VALUES ('Silmara Leite', 'Caruaru - Casa Rosa', '2026-06-13');
INSERT INTO shows (banda, local, data) VALUES ('Ceiça Moreno', 'Caruaru - Casa Rosa', '2026-06-13');
INSERT INTO shows (banda, local, data) VALUES ('Adelma Costa', 'Caruaru - Casa Rosa', '2026-06-14');
INSERT INTO shows (banda, local, data) VALUES ('Totonho', 'Caruaru - Casa Rosa', '2026-06-14');
INSERT INTO shows (banda, local, data) VALUES ('Carlinhos Pompom', 'Caruaru - Casa Rosa', '2026-06-14');
INSERT INTO shows (banda, local, data) VALUES ('Erick Moreira', 'Caruaru - Casa Rosa', '2026-06-20');
INSERT INTO shows (banda, local, data) VALUES ('Elga Nunes', 'Caruaru - Casa Rosa', '2026-06-20');
INSERT INTO shows (banda, local, data) VALUES ('Baião Plugado', 'Caruaru - Casa Rosa', '2026-06-20');
INSERT INTO shows (banda, local, data) VALUES ('Rose Santana', 'Caruaru - Casa Rosa', '2026-06-21');
INSERT INTO shows (banda, local, data) VALUES ('João Lacerda', 'Caruaru - Casa Rosa', '2026-06-21');
INSERT INTO shows (banda, local, data) VALUES ('Walkyria Mendes', 'Caruaru - Casa Rosa', '2026-06-21');
INSERT INTO shows (banda, local, data) VALUES ('Vanessa Fernandes', 'Caruaru - Casa Rosa', '2026-06-23');
INSERT INTO shows (banda, local, data) VALUES ('Forró Cigano', 'Caruaru - Casa Rosa', '2026-06-23');
INSERT INTO shows (banda, local, data) VALUES ('Anderson do Pífe', 'Caruaru - Casa Rosa', '2026-06-23');
INSERT INTO shows (banda, local, data) VALUES ('Bernadete França', 'Caruaru - Casa Rosa', '2026-06-24');
INSERT INTO shows (banda, local, data) VALUES ('Banda As Fulô', 'Caruaru - Casa Rosa', '2026-06-24');
INSERT INTO shows (banda, local, data) VALUES ('Banda do Batista (55 anos de história)', 'Caruaru - Casa Rosa', '2026-06-24');
INSERT INTO shows (banda, local, data) VALUES ('Iapone Farra', 'Caruaru - Casa Rosa', '2026-06-27');
INSERT INTO shows (banda, local, data) VALUES ('Marcelo Rossiter', 'Caruaru - Casa Rosa', '2026-06-27');
INSERT INTO shows (banda, local, data) VALUES ('Wanessa Roger', 'Caruaru - Casa Rosa', '2026-06-27');
INSERT INTO shows (banda, local, data) VALUES ('Luciana Salvador + Intervenção LGBTQIAPN+', 'Caruaru - Casa Rosa', '2026-06-28');
INSERT INTO shows (banda, local, data) VALUES ('Kaká Cantarelli + Intervenção LGBTQIAPN+', 'Caruaru - Casa Rosa', '2026-06-28');
INSERT INTO shows (banda, local, data) VALUES ('Isabela Moraes + Intervenção LGBTQIAPN+', 'Caruaru - Casa Rosa', '2026-06-28');
INSERT INTO shows (banda, local, data) VALUES ('Projeto Dominguinho (João Gomes, Mestrinho e Jota Pê)', 'Campina Grande - Parque do Povo', '2026-06-03');
INSERT INTO shows (banda, local, data) VALUES ('Solange Almeida', 'Campina Grande - Parque do Povo', '2026-06-03');
INSERT INTO shows (banda, local, data) VALUES ('Brasas do Forró', 'Campina Grande - Parque do Povo', '2026-06-03');
INSERT INTO shows (banda, local, data) VALUES ('Limão com Mel', 'Campina Grande - Parque do Povo', '2026-06-03');
INSERT INTO shows (banda, local, data) VALUES ('À Vontade (Raí Saia Rodada, Zezo e Luan)', 'Campina Grande - Parque do Povo', '2026-06-04');
INSERT INTO shows (banda, local, data) VALUES ('Mikael Santos', 'Campina Grande - Parque do Povo', '2026-06-04');
INSERT INTO shows (banda, local, data) VALUES ('Dorgival Dantas', 'Campina Grande - Parque do Povo', '2026-06-04');
INSERT INTO shows (banda, local, data) VALUES ('Samya Maia', 'Campina Grande - Parque do Povo', '2026-06-04');
INSERT INTO shows (banda, local, data) VALUES ('Wesley Safadão', 'Campina Grande - Parque do Povo', '2026-06-05');
INSERT INTO shows (banda, local, data) VALUES ('Eric Land', 'Campina Grande - Parque do Povo', '2026-06-05');
INSERT INTO shows (banda, local, data) VALUES ('Marcynho Sensação', 'Campina Grande - Parque do Povo', '2026-06-05');
INSERT INTO shows (banda, local, data) VALUES ('Deanzinho', 'Campina Grande - Parque do Povo', '2026-06-05');
INSERT INTO shows (banda, local, data) VALUES ('Henrique e Juliano', 'Campina Grande - Parque do Povo', '2026-06-06');
INSERT INTO shows (banda, local, data) VALUES ('Walkyria Santos', 'Campina Grande - Parque do Povo', '2026-06-06');
INSERT INTO shows (banda, local, data) VALUES ('Bia Frazzo', 'Campina Grande - Parque do Povo', '2026-06-06');
INSERT INTO shows (banda, local, data) VALUES ('Nathan Vinícius', 'Campina Grande - Parque do Povo', '2026-06-06');
INSERT INTO shows (banda, local, data) VALUES ('Nattanzinho Lima', 'Campina Grande - Parque do Povo', '2026-06-07');
INSERT INTO shows (banda, local, data) VALUES ('Tarcísio do Acordeon', 'Campina Grande - Parque do Povo', '2026-06-07');
INSERT INTO shows (banda, local, data) VALUES ('Raphaela Santos', 'Campina Grande - Parque do Povo', '2026-06-07');
INSERT INTO shows (banda, local, data) VALUES ('Gitana Pimentel', 'Campina Grande - Parque do Povo', '2026-06-07');
INSERT INTO shows (banda, local, data) VALUES ('Arraiá do Crescer', 'Campina Grande - Parque do Povo', '2026-06-09');
INSERT INTO shows (banda, local, data) VALUES ('Padre Nilson', 'Campina Grande - Parque do Povo', '2026-06-09');
INSERT INTO shows (banda, local, data) VALUES ('Irmã Kelly Patrícia', 'Campina Grande - Parque do Povo', '2026-06-09');
INSERT INTO shows (banda, local, data) VALUES ('Ana Clara Rocha e Ítalo Poeta', 'Campina Grande - Parque do Povo', '2026-06-09');
INSERT INTO shows (banda, local, data) VALUES ('Léo Magalhães', 'Campina Grande - Parque do Povo', '2026-06-10');
INSERT INTO shows (banda, local, data) VALUES ('Matheus Fernandes', 'Campina Grande - Parque do Povo', '2026-06-10');
INSERT INTO shows (banda, local, data) VALUES ('Banda Magníficos', 'Campina Grande - Parque do Povo', '2026-06-10');
INSERT INTO shows (banda, local, data) VALUES ('Matheuzin', 'Campina Grande - Parque do Povo', '2026-06-10');
INSERT INTO shows (banda, local, data) VALUES ('Matuê', 'Campina Grande - Parque do Povo', '2026-06-11');
INSERT INTO shows (banda, local, data) VALUES ('Jonas Esticado', 'Campina Grande - Parque do Povo', '2026-06-11');
INSERT INTO shows (banda, local, data) VALUES ('Cavaleiros do Forró', 'Campina Grande - Parque do Povo', '2026-06-11');
INSERT INTO shows (banda, local, data) VALUES ('Karkará', 'Campina Grande - Parque do Povo', '2026-06-11');
INSERT INTO shows (banda, local, data) VALUES ('Marisa Monte', 'Campina Grande - Parque do Povo', '2026-06-12');
INSERT INTO shows (banda, local, data) VALUES ('Gegê Bismarck', 'Campina Grande - Parque do Povo', '2026-06-12');
INSERT INTO shows (banda, local, data) VALUES ('Tito', 'Campina Grande - Parque do Povo', '2026-06-12');
INSERT INTO shows (banda, local, data) VALUES ('Alexandre Tan', 'Campina Grande - Parque do Povo', '2026-06-12');
INSERT INTO shows (banda, local, data) VALUES ('Henry Freitas', 'Campina Grande - Parque do Povo', '2026-06-13');
INSERT INTO shows (banda, local, data) VALUES ('Mari Fernandez', 'Campina Grande - Parque do Povo', '2026-06-13');
INSERT INTO shows (banda, local, data) VALUES ('Ávine Vinny', 'Campina Grande - Parque do Povo', '2026-06-13');
INSERT INTO shows (banda, local, data) VALUES ('Lipe Lucena', 'Campina Grande - Parque do Povo', '2026-06-13');
INSERT INTO shows (banda, local, data) VALUES ('Roberto Carlos', 'Campina Grande - Parque do Povo', '2026-06-14');
INSERT INTO shows (banda, local, data) VALUES ('Cavalo de Pau', 'Campina Grande - Parque do Povo', '2026-06-14');
INSERT INTO shows (banda, local, data) VALUES ('Juarez', 'Campina Grande - Parque do Povo', '2026-06-14');
INSERT INTO shows (banda, local, data) VALUES ('Arraiá do Crescer', 'Campina Grande - Parque do Povo', '2026-06-16');
INSERT INTO shows (banda, local, data) VALUES ('William Sanfona', 'Campina Grande - Parque do Povo', '2026-06-16');
INSERT INTO shows (banda, local, data) VALUES ('Thiago Brado', 'Campina Grande - Parque do Povo', '2026-06-16');
INSERT INTO shows (banda, local, data) VALUES ('Teto Fonseca', 'Campina Grande - Parque do Povo', '2026-06-16');
INSERT INTO shows (banda, local, data) VALUES ('Menos é Mais', 'Campina Grande - Parque do Povo', '2026-06-17');
INSERT INTO shows (banda, local, data) VALUES ('Léo Foguete', 'Campina Grande - Parque do Povo', '2026-06-17');
INSERT INTO shows (banda, local, data) VALUES ('Michelle Andrade', 'Campina Grande - Parque do Povo', '2026-06-17');
INSERT INTO shows (banda, local, data) VALUES ('Jonny Garotinho', 'Campina Grande - Parque do Povo', '2026-06-17');
INSERT INTO shows (banda, local, data) VALUES ('Matheus & Kauan', 'Campina Grande - Parque do Povo', '2026-06-18');
INSERT INTO shows (banda, local, data) VALUES ('Calcinha Preta', 'Campina Grande - Parque do Povo', '2026-06-18');
INSERT INTO shows (banda, local, data) VALUES ('Grelo', 'Campina Grande - Parque do Povo', '2026-06-18');
INSERT INTO shows (banda, local, data) VALUES ('Mexe Ville', 'Campina Grande - Parque do Povo', '2026-06-18');
INSERT INTO shows (banda, local, data) VALUES ('Iguinho e Lulinha', 'Campina Grande - Parque do Povo', '2026-06-19');
INSERT INTO shows (banda, local, data) VALUES ('Zé Cantor', 'Campina Grande - Parque do Povo', '2026-06-19');
INSERT INTO shows (banda, local, data) VALUES ('Manim Vaqueiro', 'Campina Grande - Parque do Povo', '2026-06-19');
INSERT INTO shows (banda, local, data) VALUES ('Fabiano Guimarães', 'Campina Grande - Parque do Povo', '2026-06-19');
INSERT INTO shows (banda, local, data) VALUES ('Fagner', 'Campina Grande - Parque do Povo', '2026-06-20');
INSERT INTO shows (banda, local, data) VALUES ('Garota Safada', 'Campina Grande - Parque do Povo', '2026-06-20');
INSERT INTO shows (banda, local, data) VALUES ('Ton Oliveira', 'Campina Grande - Parque do Povo', '2026-06-20');
INSERT INTO shows (banda, local, data) VALUES ('Bob Léo', 'Campina Grande - Parque do Povo', '2026-06-20');
INSERT INTO shows (banda, local, data) VALUES ('Fernandinha', 'Campina Grande - Parque do Povo', '2026-06-21');
INSERT INTO shows (banda, local, data) VALUES ('Samyra Show', 'Campina Grande - Parque do Povo', '2026-06-21');
INSERT INTO shows (banda, local, data) VALUES ('Amazan', 'Campina Grande - Parque do Povo', '2026-06-21');
INSERT INTO shows (banda, local, data) VALUES ('Raphael Moura', 'Campina Grande - Parque do Povo', '2026-06-21');
INSERT INTO shows (banda, local, data) VALUES ('Amanda Rainha da Farra', 'Campina Grande - Parque do Povo', '2026-06-22');
INSERT INTO shows (banda, local, data) VALUES ('Eliane', 'Campina Grande - Parque do Povo', '2026-06-22');
INSERT INTO shows (banda, local, data) VALUES ('Os 3 do Nordeste', 'Campina Grande - Parque do Povo', '2026-06-22');
INSERT INTO shows (banda, local, data) VALUES ('Elba Ramalho', 'Campina Grande - Parque do Povo', '2026-06-23');
INSERT INTO shows (banda, local, data) VALUES ('Guilherme Dantas', 'Campina Grande - Parque do Povo', '2026-06-23');
INSERT INTO shows (banda, local, data) VALUES ('Lucy Alves', 'Campina Grande - Parque do Povo', '2026-06-23');
INSERT INTO shows (banda, local, data) VALUES ('Capilé', 'Campina Grande - Parque do Povo', '2026-06-23');
INSERT INTO shows (banda, local, data) VALUES ('Murilo Huff', 'Campina Grande - Parque do Povo', '2026-06-24');
INSERT INTO shows (banda, local, data) VALUES ('José Augusto', 'Campina Grande - Parque do Povo', '2026-06-24');
INSERT INTO shows (banda, local, data) VALUES ('Waldonys', 'Campina Grande - Parque do Povo', '2026-06-24');
INSERT INTO shows (banda, local, data) VALUES ('Fabiana Souto', 'Campina Grande - Parque do Povo', '2026-06-24');
INSERT INTO shows (banda, local, data) VALUES ('Toque Dez', 'Campina Grande - Parque do Povo', '2026-06-25');
INSERT INTO shows (banda, local, data) VALUES ('Nuzio Medeiros', 'Campina Grande - Parque do Povo', '2026-06-25');
INSERT INTO shows (banda, local, data) VALUES ('Kadu Martins', 'Campina Grande - Parque do Povo', '2026-06-25');
INSERT INTO shows (banda, local, data) VALUES ('Jefferson Arretado', 'Campina Grande - Parque do Povo', '2026-06-25');
INSERT INTO shows (banda, local, data) VALUES ('Xand Avião', 'Campina Grande - Parque do Povo', '2026-06-26');
INSERT INTO shows (banda, local, data) VALUES ('Nattan', 'Campina Grande - Parque do Povo', '2026-06-26');
INSERT INTO shows (banda, local, data) VALUES ('Kátia e Aduílio', 'Campina Grande - Parque do Povo', '2026-06-26');
INSERT INTO shows (banda, local, data) VALUES ('Ranniery Gomes', 'Campina Grande - Parque do Povo', '2026-06-26');
INSERT INTO shows (banda, local, data) VALUES ('Zé Vaqueiro', 'Campina Grande - Parque do Povo', '2026-06-27');
INSERT INTO shows (banda, local, data) VALUES ('Felipe Amorim', 'Campina Grande - Parque do Povo', '2026-06-27');
INSERT INTO shows (banda, local, data) VALUES ('Talita Mel', 'Campina Grande - Parque do Povo', '2026-06-27');
INSERT INTO shows (banda, local, data) VALUES ('Stella Alves', 'Campina Grande - Parque do Povo', '2026-06-27');
INSERT INTO shows (banda, local, data) VALUES ('Simone Mendes', 'Campina Grande - Parque do Povo', '2026-06-28');
INSERT INTO shows (banda, local, data) VALUES ('Japãozin', 'Campina Grande - Parque do Povo', '2026-06-28');
INSERT INTO shows (banda, local, data) VALUES ('Mara Pavanelly', 'Campina Grande - Parque do Povo', '2026-06-28');
INSERT INTO shows (banda, local, data) VALUES ('Nicácia Brasil', 'Campina Grande - Parque do Povo', '2026-06-28');
INSERT INTO shows (banda, local, data) VALUES ('Priscila Senna', 'Campina Grande - Parque do Povo', '2026-06-29');
INSERT INTO shows (banda, local, data) VALUES ('Forró Real', 'Campina Grande - Parque do Povo', '2026-06-29');
INSERT INTO shows (banda, local, data) VALUES ('Bonde do Brasil', 'Campina Grande - Parque do Povo', '2026-06-29');
INSERT INTO shows (banda, local, data) VALUES ('Chambinho', 'Campina Grande - Parque do Povo', '2026-06-29');
INSERT INTO shows (banda, local, data) VALUES ('Diego Facó', 'Campina Grande - Parque do Povo', '2026-06-29');
INSERT INTO shows (banda, local, data) VALUES ('Fhop Music', 'Campina Grande - Parque do Povo', '2026-06-30');
INSERT INTO shows (banda, local, data) VALUES ('Eli Soares', 'Campina Grande - Parque do Povo', '2026-06-30');
INSERT INTO shows (banda, local, data) VALUES ('Filho do Piseiro', 'Campina Grande - Parque do Povo', '2026-07-01');
INSERT INTO shows (banda, local, data) VALUES ('Claudinei e Juliana', 'Campina Grande - Parque do Povo', '2026-07-01');
INSERT INTO shows (banda, local, data) VALUES ('Eduardinho', 'Campina Grande - Parque do Povo', '2026-07-01');
INSERT INTO shows (banda, local, data) VALUES ('Forró Pegado', 'Campina Grande - Parque do Povo', '2026-07-01');
INSERT INTO shows (banda, local, data) VALUES ('Sorriso Maroto', 'Campina Grande - Parque do Povo', '2026-07-02');
INSERT INTO shows (banda, local, data) VALUES ('Vitor Fernandes', 'Campina Grande - Parque do Povo', '2026-07-02');
INSERT INTO shows (banda, local, data) VALUES ('Mastruz com Leite', 'Campina Grande - Parque do Povo', '2026-07-02');
INSERT INTO shows (banda, local, data) VALUES ('Matheus Felipe', 'Campina Grande - Parque do Povo', '2026-07-02');
INSERT INTO shows (banda, local, data) VALUES ('Taty Girl', 'Campina Grande - Parque do Povo', '2026-07-03');
INSERT INTO shows (banda, local, data) VALUES ('Márcia Fellipe', 'Campina Grande - Parque do Povo', '2026-07-03');
INSERT INTO shows (banda, local, data) VALUES ('Toca do Vale', 'Campina Grande - Parque do Povo', '2026-07-03');
INSERT INTO shows (banda, local, data) VALUES ('Atração surpresa', 'Campina Grande - Parque do Povo', '2026-07-03');
INSERT INTO shows (banda, local, data) VALUES ('Seu Desejo', 'Campina Grande - Parque do Povo', '2026-07-04');
INSERT INTO shows (banda, local, data) VALUES ('Silvânia & Berg', 'Campina Grande - Parque do Povo', '2026-07-04');
INSERT INTO shows (banda, local, data) VALUES ('Mano Walter', 'Campina Grande - Parque do Povo', '2026-07-04');
INSERT INTO shows (banda, local, data) VALUES ('Fabrício Rodrigues', 'Campina Grande - Parque do Povo', '2026-07-04');
INSERT INTO shows (banda, local, data) VALUES ('Pablo', 'Campina Grande - Parque do Povo', '2026-07-05');
INSERT INTO shows (banda, local, data) VALUES ('Rey Vaqueiro', 'Campina Grande - Parque do Povo', '2026-07-05');
INSERT INTO shows (banda, local, data) VALUES ('Flávio José', 'Campina Grande - Parque do Povo', '2026-07-05');
INSERT INTO shows (banda, local, data) VALUES ('Yasmin Sensação', 'Campina Grande - Parque do Povo', '2026-07-05');
INSERT INTO shows (banda, local, data) VALUES ('Mais Ki Desejo', 'Tracunhaém - Pátio de Eventos', '2026-06-01');
INSERT INTO shows (banda, local, data) VALUES ('Mel com Terra', 'Tracunhaém - Pátio de Eventos', '2026-06-01');
INSERT INTO shows (banda, local, data) VALUES ('Iguinho e Lulinha', 'Tracunhaém - Pátio de Eventos', '2026-06-01');
INSERT INTO shows (banda, local, data) VALUES ('Balaio de Gatos', 'Tracunhaém - Pátio de Eventos', '2026-06-02');
INSERT INTO shows (banda, local, data) VALUES ('Rabo de Saia', 'Tracunhaém - Pátio de Eventos', '2026-06-02');
INSERT INTO shows (banda, local, data) VALUES ('Rey Vaqueiro', 'Tracunhaém - Pátio de Eventos', '2026-06-02');
INSERT INTO shows (banda, local, data) VALUES ('Mi Olywer', 'Tracunhaém - Centro', '2026-06-03');
INSERT INTO shows (banda, local, data) VALUES ('Revelação do Brega', 'Tracunhaém - Centro', '2026-06-03');
INSERT INTO shows (banda, local, data) VALUES ('Delegado e Banda', 'Tracunhaém - Centro', '2026-06-03');
INSERT INTO shows (banda, local, data) VALUES ('Eliminatórias do Concurso de Quadrilha Adulto', 'Tracunhaém - Centro', '2026-06-04');
INSERT INTO shows (banda, local, data) VALUES ('Eliminatórias do Concurso de Quadrilha Adulto', 'Tracunhaém - Centro', '2026-06-05');
INSERT INTO shows (banda, local, data) VALUES ('Janício', 'Tracunhaém - Pátio de Eventos', '2026-06-06');
INSERT INTO shows (banda, local, data) VALUES ('Tayara Andreza', 'Tracunhaém - Pátio de Eventos', '2026-06-06');
INSERT INTO shows (banda, local, data) VALUES ('Forró Retrô', 'Tracunhaém - Pátio de Eventos', '2026-06-06');
INSERT INTO shows (banda, local, data) VALUES ('1ª Feira de Artesanato', 'Tracunhaém - Centro', '2026-06-07');
INSERT INTO shows (banda, local, data) VALUES ('Forró dos Idosos', 'Tracunhaém - Centro', '2026-06-07');
INSERT INTO shows (banda, local, data) VALUES ('Festival de Ciranda', 'Tracunhaém - Centro', '2026-06-07');
INSERT INTO shows (banda, local, data) VALUES ('Gabriel Cantor', 'Tracunhaém - Pátio de Eventos', '2026-06-08');
INSERT INTO shows (banda, local, data) VALUES ('Capital do Sol', 'Tracunhaém - Pátio de Eventos', '2026-06-08');
INSERT INTO shows (banda, local, data) VALUES ('Tarcísio do Acordeon', 'Tracunhaém - Pátio de Eventos', '2026-06-08');
INSERT INTO shows (banda, local, data) VALUES ('Festival de Quadrilhas Infantil', 'Tracunhaém - Centro', '2026-06-09');
INSERT INTO shows (banda, local, data) VALUES ('Dhyeguinho', 'Tracunhaém - Centro', '2026-06-10');
INSERT INTO shows (banda, local, data) VALUES ('Vagner Boladão', 'Tracunhaém - Centro', '2026-06-10');
INSERT INTO shows (banda, local, data) VALUES ('Francis Jr.', 'Tracunhaém - Centro', '2026-06-10');
INSERT INTO shows (banda, local, data) VALUES ('Final do Concurso de Quadrilhas Adulto e Infantil', 'Tracunhaém - Centro', '2026-06-11');
INSERT INTO shows (banda, local, data) VALUES ('Fábio e Banda', 'Tracunhaém - Pátio de Eventos', '2026-06-12');
INSERT INTO shows (banda, local, data) VALUES ('Forrozão Chacal', 'Tracunhaém - Pátio de Eventos', '2026-06-12');
INSERT INTO shows (banda, local, data) VALUES ('Banda Aquarius', 'Tracunhaém - Pátio de Eventos', '2026-06-12');
INSERT INTO shows (banda, local, data) VALUES ('Festa Católica', 'Tracunhaém - Centro', '2026-06-13');
INSERT INTO shows (banda, local, data) VALUES ('Ranniery Gomes', 'João Pessoa - Parque Sólon de Lucena (Palco Principal)', '2026-06-19');
INSERT INTO shows (banda, local, data) VALUES ('Banda Cascavel', 'João Pessoa - Parque Sólon de Lucena (Palco Principal)', '2026-06-19');
INSERT INTO shows (banda, local, data) VALUES ('Mara Pavanelly', 'João Pessoa - Parque Sólon de Lucena (Palco Principal)', '2026-06-20');
INSERT INTO shows (banda, local, data) VALUES ('Felipe Santos', 'João Pessoa - Parque Sólon de Lucena (Palco Principal)', '2026-06-20');
INSERT INTO shows (banda, local, data) VALUES ('Raifi Sousa', 'João Pessoa - Parque Sólon de Lucena (Palco Principal)', '2026-06-20');
INSERT INTO shows (banda, local, data) VALUES ('Cavalo de Pau', 'João Pessoa - Parque Sólon de Lucena (Palco Principal)', '2026-06-21');
INSERT INTO shows (banda, local, data) VALUES ('Luka Bass', 'João Pessoa - Parque Sólon de Lucena (Palco Principal)', '2026-06-21');
INSERT INTO shows (banda, local, data) VALUES ('Fabrício Rodrigues', 'João Pessoa - Parque Sólon de Lucena (Palco Principal)', '2026-06-21');
INSERT INTO shows (banda, local, data) VALUES ('Babau Joaquim Guedes do Mestre Vavau', 'João Pessoa - Parque Sólon de Lucena (Cultura Popular)', '2026-06-21');
INSERT INTO shows (banda, local, data) VALUES ('Boi de Reis Estrela do Norte', 'João Pessoa - Parque Sólon de Lucena (Cultura Popular)', '2026-06-21');
INSERT INTO shows (banda, local, data) VALUES ('Osmídio Neto', 'João Pessoa - Parque Sólon de Lucena (Palco Principal)', '2026-06-22');
INSERT INTO shows (banda, local, data) VALUES ('Amanda Rainha da Farra', 'João Pessoa - Parque Sólon de Lucena (Palco Principal)', '2026-06-22');
INSERT INTO shows (banda, local, data) VALUES ('Forró Pegado', 'João Pessoa - Parque Sólon de Lucena (Palco Principal)', '2026-06-22');
INSERT INTO shows (banda, local, data) VALUES ('Cangaceiras de Lampião', 'João Pessoa - Parque Sólon de Lucena (Cultura Popular)', '2026-06-22');
INSERT INTO shows (banda, local, data) VALUES ('Cavalo Marinho Raiz Cultural', 'João Pessoa - Parque Sólon de Lucena (Cultura Popular)', '2026-06-22');
INSERT INTO shows (banda, local, data) VALUES ('Gitana Pimentel', 'João Pessoa - Parque Sólon de Lucena (Palco Principal)', '2026-06-23');
INSERT INTO shows (banda, local, data) VALUES ('Raphaela Santos', 'João Pessoa - Parque Sólon de Lucena (Palco Principal)', '2026-06-23');
INSERT INTO shows (banda, local, data) VALUES ('Danieze Santiago', 'João Pessoa - Parque Sólon de Lucena (Palco Principal)', '2026-06-23');
INSERT INTO shows (banda, local, data) VALUES ('Grupo de Xaxado Moleque Ricardo', 'João Pessoa - Parque Sólon de Lucena (Cultura Popular)', '2026-06-23');
INSERT INTO shows (banda, local, data) VALUES ('Cavalo Marinho Infantil Sementes', 'João Pessoa - Parque Sólon de Lucena (Cultura Popular)', '2026-06-23');
INSERT INTO shows (banda, local, data) VALUES ('Banda Encantus', 'João Pessoa - Parque Sólon de Lucena (Palco Principal)', '2026-06-24');
INSERT INTO shows (banda, local, data) VALUES ('Banda Libanos', 'João Pessoa - Parque Sólon de Lucena (Palco Principal)', '2026-06-24');
INSERT INTO shows (banda, local, data) VALUES ('Grupo Junino Maria Cangaceira', 'João Pessoa - Parque Sólon de Lucena (Cultura Popular)', '2026-06-24');
INSERT INTO shows (banda, local, data) VALUES ('Vó Mera e Suas Netinhas', 'João Pessoa - Parque Sólon de Lucena (Cultura Popular)', '2026-06-24');
INSERT INTO shows (banda, local, data) VALUES ('Ed Carlos', 'Bezerros - Serra Negra (Palco Principal)', '2026-06-13');
INSERT INTO shows (banda, local, data) VALUES ('Marcão Noventta', 'Bezerros - Serra Negra (Palco Principal)', '2026-06-13');
INSERT INTO shows (banda, local, data) VALUES ('Petrúcio Amorim', 'Bezerros - Serra Negra (Palco Principal)', '2026-06-13');
INSERT INTO shows (banda, local, data) VALUES ('Waldonys + Jogo do Brasil', 'Bezerros - Serra Negra (Palco Principal)', '2026-06-13');
INSERT INTO shows (banda, local, data) VALUES ('Luizinho Moreno', 'Bezerros - Serra Negra (Palco Principal)', '2026-06-14');
INSERT INTO shows (banda, local, data) VALUES ('Daniel Gouveia', 'Bezerros - Serra Negra (Palco Principal)', '2026-06-14');
INSERT INTO shows (banda, local, data) VALUES ('Victor Ferrari', 'Bezerros - Serra Negra (Palco Principal)', '2026-06-14');
INSERT INTO shows (banda, local, data) VALUES ('Santanna - O Cantador', 'Bezerros - Serra Negra (Palco Principal)', '2026-06-14');
INSERT INTO shows (banda, local, data) VALUES ('Anderson Alves', 'Bezerros - Serra Negra (Palco Principal)', '2026-06-14');
INSERT INTO shows (banda, local, data) VALUES ('Ciel Santos', 'Bezerros - Serra Negra (Palco Principal)', '2026-06-20');
INSERT INTO shows (banda, local, data) VALUES ('Josildo Sá', 'Bezerros - Serra Negra (Palco Principal)', '2026-06-20');
INSERT INTO shows (banda, local, data) VALUES ('Assisão', 'Bezerros - Serra Negra (Palco Principal)', '2026-06-20');
INSERT INTO shows (banda, local, data) VALUES ('Emerson Cavalcante', 'Bezerros - Serra Negra (Palco Principal)', '2026-06-20');
INSERT INTO shows (banda, local, data) VALUES ('Fabiana Pimentinha', 'Bezerros - Serra Negra (Palco Principal)', '2026-06-21');
INSERT INTO shows (banda, local, data) VALUES ('Henrique Barbosa', 'Bezerros - Serra Negra (Palco Principal)', '2026-06-21');
INSERT INTO shows (banda, local, data) VALUES ('Almir Rouche', 'Bezerros - Serra Negra (Palco Principal)', '2026-06-21');
INSERT INTO shows (banda, local, data) VALUES ('Assum Preto', 'Bezerros - Serra Negra (Palco Principal)', '2026-06-21');
INSERT INTO shows (banda, local, data) VALUES ('Higor Henrique', 'Bezerros - Serra Negra (Palco Principal)', '2026-06-21');
INSERT INTO shows (banda, local, data) VALUES ('Samara Costa', 'Bezerros - Serra Negra (Palco Principal)', '2026-06-23');
INSERT INTO shows (banda, local, data) VALUES ('Dudu do Acordeon', 'Bezerros - Serra Negra (Palco Principal)', '2026-06-23');
INSERT INTO shows (banda, local, data) VALUES ('Jorge de Altinho', 'Bezerros - Serra Negra (Palco Principal)', '2026-06-23');
INSERT INTO shows (banda, local, data) VALUES ('Geraldinho Lins', 'Bezerros - Serra Negra (Palco Principal)', '2026-06-23');
INSERT INTO shows (banda, local, data) VALUES ('Bruninho Lima', 'Bezerros - Serra Negra (Palco Principal)', '2026-06-23');
INSERT INTO shows (banda, local, data) VALUES ('Silvério Pessoa', 'Bezerros - Serra Negra (Palco Principal)', '2026-06-24');
INSERT INTO shows (banda, local, data) VALUES ('Joyce Alane', 'Bezerros - Serra Negra (Palco Principal)', '2026-06-24');
INSERT INTO shows (banda, local, data) VALUES ('Juarez', 'Bezerros - Serra Negra (Palco Principal)', '2026-06-24');
INSERT INTO shows (banda, local, data) VALUES ('Lady Falcão + Jogo do Brasil', 'Bezerros - Serra Negra (Palco Principal)', '2026-06-24');
INSERT INTO shows (banda, local, data) VALUES ('Rei do Cangaço', 'Bezerros - Serra Negra (Palco Principal)', '2026-06-27');
INSERT INTO shows (banda, local, data) VALUES ('Irah Caldeira', 'Bezerros - Serra Negra (Palco Principal)', '2026-06-27');
INSERT INTO shows (banda, local, data) VALUES ('Amazan', 'Bezerros - Serra Negra (Palco Principal)', '2026-06-27');
INSERT INTO shows (banda, local, data) VALUES ('Cristina Amaral', 'Bezerros - Serra Negra (Palco Principal)', '2026-06-27');
INSERT INTO shows (banda, local, data) VALUES ('Walter Lins', 'Bezerros - Serra Negra (Palco Principal)', '2026-06-27');
INSERT INTO shows (banda, local, data) VALUES ('Morganna Bernardo', 'Bezerros - Serra Negra (Palco Principal)', '2026-06-28');
INSERT INTO shows (banda, local, data) VALUES ('Flávio Leandro', 'Bezerros - Serra Negra (Palco Principal)', '2026-06-28');
INSERT INTO shows (banda, local, data) VALUES ('Pau no Xote', 'Bezerros - Serra Negra (Palco Principal)', '2026-06-28');
INSERT INTO shows (banda, local, data) VALUES ('Cezzinha', 'Bezerros - Serra Negra (Palco Principal)', '2026-06-28');
INSERT INTO shows (banda, local, data) VALUES ('Amannda Leão', 'Bezerros - Serra Negra (Palco Principal)', '2026-06-28');
INSERT INTO shows (banda, local, data) VALUES ('Gusttavo Lima', 'Surubim - Polo Vaquejada', '2026-06-18');
INSERT INTO shows (banda, local, data) VALUES ('Bruno e Marrone', 'Surubim - Polo Vaquejada', '2026-06-18');
INSERT INTO shows (banda, local, data) VALUES ('Tarcísio do Acordeon', 'Surubim - Polo Vaquejada', '2026-06-18');
INSERT INTO shows (banda, local, data) VALUES ('PV Calado', 'Surubim - Polo Vaquejada', '2026-06-18');
INSERT INTO shows (banda, local, data) VALUES ('Leonardo', 'Surubim - Polo Vaquejada', '2026-06-20');
INSERT INTO shows (banda, local, data) VALUES ('Priscila Senna', 'Surubim - Polo Vaquejada', '2026-06-20');
INSERT INTO shows (banda, local, data) VALUES ('Raphaela Santos', 'Surubim - Polo Vaquejada', '2026-06-20');
INSERT INTO shows (banda, local, data) VALUES ('Valda Sedicias', 'Surubim - Polo Vaquejada', '2026-06-20');
INSERT INTO shows (banda, local, data) VALUES ('Wesley Safadão', 'Surubim - Polo Vaquejada', '2026-06-25');
INSERT INTO shows (banda, local, data) VALUES ('Natanzinho Lima', 'Surubim - Polo Vaquejada', '2026-06-25');
INSERT INTO shows (banda, local, data) VALUES ('Rey Vaqueiro', 'Surubim - Polo Vaquejada', '2026-06-25');
INSERT INTO shows (banda, local, data) VALUES ('Eric Land', 'Surubim - Polo Vaquejada', '2026-06-25');
INSERT INTO shows (banda, local, data) VALUES ('Henrique e Juliano', 'Surubim - Polo Vaquejada', '2026-06-26');
INSERT INTO shows (banda, local, data) VALUES ('Pablo', 'Surubim - Polo Vaquejada', '2026-06-26');
INSERT INTO shows (banda, local, data) VALUES ('Grelo', 'Surubim - Polo Vaquejada', '2026-06-26');
INSERT INTO shows (banda, local, data) VALUES ('Calcinha Preta', 'Surubim - Polo Vaquejada', '2026-06-26');
INSERT INTO shows (banda, local, data) VALUES ('Patrick Costa', 'Surubim - Polo Vaquejada', '2026-06-26');
INSERT INTO shows (banda, local, data) VALUES ('Luan Santana', 'Surubim - Polo Vaquejada', '2026-06-27');
INSERT INTO shows (banda, local, data) VALUES ('Avine Vinny', 'Surubim - Polo Vaquejada', '2026-06-27');
INSERT INTO shows (banda, local, data) VALUES ('João Gomes', 'Surubim - Polo Vaquejada', '2026-06-27');
INSERT INTO shows (banda, local, data) VALUES ('Kadu Martins', 'Surubim - Polo Vaquejada', '2026-06-27');
INSERT INTO shows (banda, local, data) VALUES ('Diego Vumbora', 'Surubim - Vila do Forró', '2026-06-12');
INSERT INTO shows (banda, local, data) VALUES ('Mel com Terra', 'Surubim - Vila do Forró', '2026-06-12');
INSERT INTO shows (banda, local, data) VALUES ('Rafa Alyce BB', 'Surubim - Vila do Forró', '2026-06-13');
INSERT INTO shows (banda, local, data) VALUES ('Assisão', 'Surubim - Vila do Forró', '2026-06-13');
INSERT INTO shows (banda, local, data) VALUES ('Ruan Vaqueirinho', 'Surubim - Vila do Forró', '2026-06-14');
INSERT INTO shows (banda, local, data) VALUES ('Vitor Vaqueiro', 'Surubim - Vila do Forró', '2026-06-14');
INSERT INTO shows (banda, local, data) VALUES ('Geraldinho Lins', 'Surubim - Vila do Forró', '2026-06-14');
INSERT INTO shows (banda, local, data) VALUES ('Arraiá da 3ª Idade', 'Surubim - Vila do Forró', '2026-06-16');
INSERT INTO shows (banda, local, data) VALUES ('Alex Nascimento', 'Surubim - Vila do Forró', '2026-06-16');
INSERT INTO shows (banda, local, data) VALUES ('Encontro de quadrilhas', 'Surubim - Vila do Forró', '2026-06-17');
INSERT INTO shows (banda, local, data) VALUES ('Eugênio Sa', 'Surubim - Vila do Forró', '2026-06-18');
INSERT INTO shows (banda, local, data) VALUES ('Pedro Henrique', 'Surubim - Vila do Forró', '2026-06-19');
INSERT INTO shows (banda, local, data) VALUES ('Namara Bello', 'Surubim - Vila do Forró', '2026-06-19');
INSERT INTO shows (banda, local, data) VALUES ('Moura Fontan', 'Surubim - Vila do Forró', '2026-06-20');
INSERT INTO shows (banda, local, data) VALUES ('Valda Sedicias', 'Surubim - Vila do Forró', '2026-06-21');
INSERT INTO shows (banda, local, data) VALUES ('Sirano e Sirino', 'Surubim - Vila do Forró', '2026-06-21');
INSERT INTO shows (banda, local, data) VALUES ('Marcilio Arruda', 'Surubim - Vila do Forró', '2026-06-21');
INSERT INTO shows (banda, local, data) VALUES ('Deka Vanerão', 'Surubim - Vila do Forró', '2026-06-23');
INSERT INTO shows (banda, local, data) VALUES ('Mistura Fina', 'Surubim - Vila do Forró', '2026-06-23');
INSERT INTO shows (banda, local, data) VALUES ('Vilões do Forró', 'Surubim - Vila do Forró', '2026-06-23');
INSERT INTO shows (banda, local, data) VALUES ('Fabinho Moral', 'Surubim - Vila do Forró', '2026-06-24');
INSERT INTO shows (banda, local, data) VALUES ('Luan Douglas', 'Surubim - Vila do Forró', '2026-06-24');
INSERT INTO shows (banda, local, data) VALUES ('João Neto', 'Surubim - Vila do Forró', '2026-06-25');
INSERT INTO shows (banda, local, data) VALUES ('Mastigados do Forró', 'Surubim - Vila do Forró', '2026-06-26');
INSERT INTO shows (banda, local, data) VALUES ('Gyl Masseta', 'Surubim - Vila do Forró', '2026-06-27');
INSERT INTO shows (banda, local, data) VALUES ('Capim com Mel', 'Surubim - Vila do Forró', '2026-06-28');
INSERT INTO shows (banda, local, data) VALUES ('Guilherme Ferri', 'Surubim - Vila do Forró', '2026-06-28');
INSERT INTO shows (banda, local, data) VALUES ('Geiza Santos', 'Surubim - Vila do Forró', '2026-06-28');
